
export default {
	getWorkordersList: (location, arrivalDate, departureDate, checkLocation) => 'WorkOrders/getList?locationId=' + location + 'arrivalDate=' + arrivalDate + '&departureDate=' + departureDate + '&applicationType=SB&checkLocation=' + checkLocation,
	getList: 'WorkOrders/getList?isServiceRequest=true&checkLocation=true&applicationType=MBN&locationId=null',
	getSbList: (id, yesterday) => 'WorkOrders/getSbList?locationId=' + id + '&arrivalDate=' + yesterday,
	getSbList2: (id, today, tomorrow, params) => 'WorkOrders/getSbList2?locationId=' + id + '&arrivalDate=' + today + '&departureDate=' + tomorrow + params,
	getSbList2Count: (id, today, tomorrow) => 'WorkOrders/getSbList2Count?locationId=' + id + '&arrivalDate=' + today + '&departureDate=' + tomorrow,
	getWorkordersByIds: (ids) => 'WorkOrders/getWorkordersByIds?ids=[' + ids + ']',
	getWorkordersByInRollingStock: (id) => 'WorkOrders/getWorkordersByInRollingStock?inRollingStock=' + id,
	getWoByMaterialNumber: (ids) => 'WorkOrders/getWoByMaterialNumber?materialNumber=' + ids,
	getBWORelatedWO: (id) => 'WorkOrders/getBWORelatedWO?workOrderId=' + id,
	removeDuplicates: 'WorkOrders/removeDuplicates',
	searchDuplicates: 'WorkOrders/searchDuplicates',
	getCommodityGroups: 'WorkOrders/getCommodityGroups',
	getBWOWo: 'WorkOrders/getBWOWo?limit=1000',
	planSelection: 'WorkOrders/planSelection',
	saveWorkOrder: 'WorkOrders/saveWorkOrder',
	updateWorkOrder: (id) => `WorkOrders/${id}`,
	changeNtLocationType: 'WorkOrders/changeNtLocationType',
	planWO: 'WorkOrders/planWO',
	approveWO: 'WorkOrders/approveWO',
	resetWO: 'WorkOrders/resetWorkOrder',
	assignBWOwo: 'WorkOrders/assignBWOwo',
	getMobileTeamsWo: 'WorkOrders/getMobileTeamsWo',
	setKlantBehoefte: 'WorkOrders/setKlantbehoefte',
	getListServiceRequestsMBN2: 'WorkOrders/getSRMBNWo',
	linkWorkorder: 'WorkOrders/linkWorkOrder',
	unLinkWorkorder: 'WorkOrders/unLinkWorkorder',
	assignSR: 'WorkOrders/assignSR',
	//REMOVE THIS METHOD IN SPRINT 44
	resetBWO: 'WorkOrders/resetBWOwo',
	//
	changeStatusBWOwo: 'WorkOrders/changeStatusBWOwo',
	planBWO: 'WorkOrders/planBWOwo',
	fillBWO: 'WorkOrders/fillBWO',
	deleteWO: 'WorkOrders/deleteWO',
	resetWorkOrders: 'WorkOrders/resetWorkOrders',
	getDetail: (id) => 'WorkOrders/' + id,
	getFilteredDetail: (id, filter) => 'WorkOrders/' + id + '?filter=' + filter,
	getMonitorList: 'WorkOrders/getMonitorPageWo'
}
